apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: marketsummary
    context: .
deploy:
  helm:
    releases:
      - name: marketsummary
        wait: true
        chartPath: ./charts/marketsummary
        values:
          image: marketsummary
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"
          productName: "{{.PRODUCT_NAME}}"
          nodeEnv: "{{.NODE_ENV}}"
        setValues:
          hpa.enabled: true

